#cloud-config
ssh_authorized_keys:
%{ for key in ssh_authorized_keys }
  - ${key}
%{ endfor }

write-kubeconfig-mode: "0644"

users:
  - default
  - name: rke2
    homedir: /var/lib/rancher/rke2
    system: true
